# Generated by Django 2.0.6 on 2018-07-26 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_order_waiters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealstoorder',
            old_name='meals',
            new_name='meal',
        ),
        migrations.RenameField(
            model_name='mealstoorder',
            old_name='orders',
            new_name='order',
        ),
    ]
