# Generated by Django 2.0.6 on 2018-07-17 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_auto_20180717_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='service_fee',
            new_name='percentage',
        ),
    ]
