# Generated by Django 2.0.6 on 2018-07-17 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0004_auto_20180717_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='total_sum',
            new_name='totalsum',
        ),
    ]
