# Generated by Django 2.0.6 on 2018-07-17 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0005_auto_20180717_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealstoorder',
            options={'verbose_name_plural': 'MealsToOrders'},
        ),
        migrations.AlterField(
            model_name='mealstoorder',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MealsToOrder', to='CRM.Meal'),
        ),
        migrations.AlterField(
            model_name='mealstoorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MealsToOrder', to='CRM.Order'),
        ),
    ]
