# Generated by Django 2.0.6 on 2018-07-18 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0007_auto_20180717_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Order', to='CRM.Role'),
        ),
    ]
