# Generated by Django 2.0.6 on 2018-07-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0011_auto_20180718_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='order',
            new_name='orders',
        ),
        migrations.RenameField(
            model_name='check',
            old_name='percentage',
            new_name='percentages',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='table',
            new_name='tables',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='users',
        ),
        migrations.RemoveField(
            model_name='check',
            name='totalsum',
        ),
        migrations.AddField(
            model_name='order',
            name='totalsum',
            field=models.FloatField(null=True),
        ),
    ]
