# Generated by Django 2.0.6 on 2018-07-18 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0013_auto_20180718_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='totalsum',
        ),
    ]
