# Generated by Django 2.0.6 on 2018-07-18 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0014_remove_check_totalsum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='meals',
        ),
    ]
